### ISSUE TITLE
Display Context (dcontext) option does not format known currencies when transactions are not directly declared in the main beancount file

### ISSUE THREAD

**Issue by papageno** [beancount/beancount#678] opened 2021-09-28 05:30 UTC
Hi.

As stated in title, Display Context (dcontext) option does not format known currencies, i.e. USD, EUR, etc. when transactions are not in the main beancount file (usually `main.bean` in the root of ledger folder, or saying the file that is executed within `bean-check` or `bean-web` script).

I am using 'fava' to check whether `dcontext` option is applied. (Maybe this is not a good idea, but I'm still struggling with reading beancount's API docs 😂)

Given the following `main.bean` where transactions are directly declared.

```
main.bean
...
2021-09-28 *
  Assets:Cash                                       100,000 JPY
  Assets:Cash                                      1,000.00 USD
  Assets:Cash                                        500.25 EUR
  Equity:Opening-Balances
...
```

`fava`'s option page (`http://localhost:5000/ledger-title/options/`) indicates the `dcontext` option as

```	
EUR             : sign=0   integer_max=3   fractional_common=2   fractional_max=2   "000.00" "000.00"
JPY             : sign=0   integer_max=6   fractional_common=0   fractional_max=0   "000000" "000000"
USD             : sign=0   integer_max=4   fractional_common=2   fractional_max=2   "0000.00" "0000.00"
__default__     : sign=0   integer_max=1   fractional_common=_   fractional_max=_   "0.*" "0.*"
```

While if transactions are '`include`d' from another file (saying `transactions.bean`), instead of being directly declared in `main.bean`,

```
main.bean
...
include "transactions.bean"
...
```

```
transactions.bean
...
2021-09-28 *
  Assets:Cash                                       100,000 JPY
  Assets:Cash                                      1,000.00 USD
  Assets:Cash                                        500.25 EUR
  Equity:Opening-Balances
...
```

`fava`'s option page (`http://localhost:5000/ledger-title/options/`) will indicate the `dcontext` option as

```
__default__     : sign=0   integer_max=1   fractional_common=_   fractional_max=_   "0.*" "0.*"
```

Those formatting options for known currencies are gone.

**Comment by dnicolodi** [comment] 2021-09-28 06:30
I don't know what Fava displays in its options page but this seems to be a duplicate of #653 (which is itself a duplicate of other issues I don't have time to look up now). Please refer to the explanation there remembering that the display context inferred from the file content is stored as an option when parsing.

**Closed as completed** 2021-09-28 06:33 UTC
